### ISSUE TITLE
Data hack tomorrow: Police Violence

### ISSUE THREAD

**Issue by connor11528** [sfbrigade/data-science-wg#23]
Datasets on police violence: https://numeracy.co/t/policeviolence 

Props to @enjalot: http://www.meetup.com/Bay-Area-d3-User-Group/events/229131683/

**Comment by judecalvillo** [comment]
Thanks for the heads up, @cleechtech and @enjalot. I'll let the team know. Hopefully one or more of us can make it out there.

Best of luck in your prep, and happy hacking to you all!

-Jude
