### ISSUE TITLE
fire risk bad hyperlink

### ISSUE THREAD

**Issue by mikezawitkowski** [sfbrigade/data-science-wg#28]
Steps to repro:
- go to homepage https://github.com/sfbrigade/data-science-wg
- under Current Initiatives click "Predicting Relative Risk of Fire in SF's Buildings"

I thought it would lead to a fire risk specific page, but it just points to this url: https://github.com/sfbrigade/data-science-wg#

This behavior surprised me, what is the process for getting this behvior improved?

**Comment by judecalvillo** [comment]
It's behaving fine, Mike. You guys just recently created the associated repo, so I'll update the link shortly.

**Comment by mikezawitkowski** [comment]
Thanks Jude!
