### ISSUE TITLE
README link broken

### ISSUE THREAD

**Issue by elenapalesis** [sfbrigade/data-science-wg#4]
Links redirect to the main repo:
- **ParkSafe GIS coordinate realignment (w/street paths) >>**
- **Interactive visualization of SF's building emissions and energy use >>**
- **MarbleTree: Geo-aggregating mental health resource data >>**
- **Adopt-a-Drain: Predicting flooded drains (per drain, zip, and/or day) >>**

**Comment by judecalvillo** [comment]
Thx, Elena. Yeah, some links were simply blank anchors, because those projects hadn't yet initialized their repos. I'll check back with the relevant projects and see if we can update these links soon.

**Comment by elenapalesis** [comment]
I thought that might be the case!

**Comment by judecalvillo** [comment]
READMEs updated, including 311.
